### ISSUE TITLE
Please make sure platformio-atom-ide-terminal is installed and is active

### ISSUE THREAD

**Issue by 2manyvcos** [bhargav175/clickable-npm-scripts#2]
The message is displayed when trying to run a script.

platformio-ide-terminal is installed and enabled and works like expected.

This problem only occures after restarting atom. When I uninstall platformio-ide-terminal and clickable-npm-scripts and reinstall them it works until I restart atom again.

![image](https://cloud.githubusercontent.com/assets/4709780/25182506/20da7e04-2515-11e7-9a38-e5f3d5c17d08.png)

**Comment by imbhargav5** [comment]
@AaronBurmeister Thanks! On it.

**Comment by imbhargav5** [comment]
The reason was that the platform-ide-terminal dependency was utilised incorrectly. That is fixed now. Closing this issue now.  Published v3.7.1. Please install that version and let me know if you run into errors.
