### ISSUE TITLE
Auto-reload on package.json change

### ISSUE THREAD

**Issue by 2manyvcos** [bhargav175/clickable-npm-scripts#3]
Hello there,

it would be nice if the module would reload the script list when the package.json changes.
Alternatively I would love a reload command.

**Comment by imbhargav5** [comment]
Hey, that's a good suggestion. Would you like to try submitting a pull request for the same?

**Comment by 2manyvcos** [comment]
Sure. Will work on it ASAP.

**Comment by imbhargav5** [comment]
Awesome. Thanks @AaronBurmeister
